# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  
pod 'Firebase/Core'	
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SwiftyJSON'

  # Pods for ios-app

  target 'ios-appTests' do
    inherit! :search_paths
    # Pods for testing

pod 'Firebase/Core'	
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'SwiftyJSON'
  end

  target 'ios-appUITests' do
    inherit! :search_paths
    # Pods for testing.

  end

end
